# This workflow will do a clean install of your theme's dependencies and attempt to bundle the theme with Stencil CLI.
# If the theme fails to bundle, you can review the error logs to find out why.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Theme Bundling Test

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node }}

    - name: npm cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Stencil CLI Dependency
      run: npm install -g @bigcommerce/stencil-cli

    - name: Install Theme Dependencies
      run: npm ci

    - name: Grunt Check
      run: npx grunt check

    - name: Validate theme successfully bundles
      run: npx stencil bundle --name bundle

    - name: Upload bundled theme
      uses: actions/upload-artifact@v2
      with:
        name: Bundled Theme
        path: bundle.zip

    - name: Upload bundle analysis
      uses: actions/upload-artifact@v2
      with:
        name: Webpack Analysis
        path: assets/dist/report.html

